spring:
  cache:
    redis:
      time-to-live: 5000000
      cache-names: blogstack-user-management
      key-prefix: blogstack
  redis:
    host: ec2-3-110-224-124.ap-south-1.compute.amazonaws.com
    port: 6379
  main:
    allow-bean-definition-overriding: true
  application:
    name: BlogStackIAMService
  datasource:
    url: jdbc:postgresql://ec2-3-110-224-124.ap-south-1.compute.amazonaws.com:5432/blogstackusermanagement
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9095

iam-service-version: v1.0

cloud:
  aws:
    credentials:
      access-key: AKIAXFYS2UY4HNPCI35G
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: blogstack-profile-photo
  aws:
    hostname: ec2-3-110-224-124.ap-south-1.compute.amazonaws.com
