spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${MASTER_SERVICE_APPLICATION_NAME:BlogStackIAMService}
  profiles.active: local
  webflux:
    base-path: ${MASTER_SERVICE_BASE_PATH:/iam-management}

  datasource:
    url: jdbc:postgresql://localhost:8080/BlogStackIAMService
    username: postgres
    password: root
    hikari:
      minimum-idle: ${MASTER_SERVICE_DATABASE_INITIAL_POOL_SIZE:5}
      maximum-pool-size: ${MASTER_SERVICE_DATABASE_MAXIMUM_POOL_SIZE:20}
      idle-timeout: 30000
      pool-name: ${MASTER_SERVICE_DATABASE_POOL_NAME:MasterServicePool}
      max-lifetime: 2000000
      auto-commit: false
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
#  liquibase:
#    change-log: classpath:db/changelog/changelog.sql
#    url: ${MASTER_SERVICE_DATABASE_LIQUIBASE_URL:jdbc:postgresql://sudais-master-mvp-dev.cwgicxdi768g.me-central-1.rds.amazonaws.com/sudais-admin}
#    user: ${MASTER_SERVICE_DATABASE_USERNAME:sudais_admin}
#    password: ${MASTER_SERVICE_DATABASE_PASSWORD:alSuDa!s#2023}
#    database-change-log-table: databasechangelog_alsudais_master_service
#    database-change-log-lock-table: databasechangeloglock_alsudais_master_service

server:
  port: ${MASTER_SERVICE_PORT:8083}
  error.whitelabel.enabled: false
  http2.enabled: ${HTTP2_ENABLE:true}

grpc:
  client:
    iam-grpc-service:
      address: static://localhost:7071
      negotiationType: plaintext

management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

iam-service-version: v1.0

openapi3:
  group: Master
  package.to.scan: com.alsudais
  title: Master Service
  description: Master Service
  version: Version 1.0.0
  contact:
    name: Al Sudais
    url: https://alsudais.com
    email: admin@alsudais.com